### ISSUE TITLE
Database restores

### ISSUE THREAD

**Issue by oubiwann** [oxur/rucksack#44]
Features and/or tasks:
  * [ ] Update the `App` struct to include a field for the most recent backup filename
  * [x] Refactor `db.close()` to pull out backup logic
    * [x] create a new `backup` method
    * [ ] include the ability to include a tag for annoation (e.g., <original DB file>-backup-<date>-<TAG>)
  * [ ] Add a `backup` method to the `App` struct
    * this will call the db's `backup` method
    * and set the App's `latest_backup` field
  * [ ] Add a `replace` method to the `DB` struct
    * this will accept a new dash_map as input
    * and replace the current in-memory dash_map on DB with the given one
  * [ ] Add a `restore` method on `App`
    * [ ] this will call `db.replace` passing `app.latest_backup`
    * [ ] it will also null out `app.latest_backup`
  * [ ] Add a `restore_from_file` method on `App`
    * [ ] this will call `db.replace` with the given file
    * [ ] it will also null out `app.latest_backup`
  * [x] #48

Note that this set of features provides a workaround for databases that become corrupted, allowing for the easy restore with a previous backup. A long-term fix will come with a new backend for local storage.

Blocks:
* #41

**Comment by oubiwann** [comment]
I don't think we need this at the app level. It's been implemented at the db level just fine.
