### ISSUE TITLE
Add support for versioning schemas

### ISSUE THREAD

**Issue by oubiwann** [oxur/rucksack#54]
* [ ] All records need to be versioned:
  * [ ] Metadata
  * [ ] Creds
  * [ ] EncryptedRecord
  * [ ] DecryptedRecord
* [ ] The DB struct itself needs to be versioned, too
* [ ] The version to use needs to be configurable
* [ ] Attempting to load records with with different versions than configured needs to err-out
* [ ] Alternatively, the use may be prompted to upgrade and/or downgrade
* [ ] Migrations to/from versions need to be supported
* [ ] DBs and records of specific versions need to be easily created
* [ ] Add an `auto-upgrade` flag to the CLI

**Comment by oubiwann** [comment]
Ohhhh, nice: https://github.com/doctorn/obake

**Comment by oubiwann** [comment]
Ugh, not so nice. Also, been reading advice against this sort of approach by Rustaceans. Might just have a policy / convention for users to "export before you upgrade; upgrade, then import" ...

**Comment by oubiwann** [comment]
Yeah ... not going to do this.
