### ISSUE TITLE
Support various data retention policies

### ISSUE THREAD

**Issue by oubiwann** [oxur/rucksack#62]
Due to the issue in #59, we're taking a more creative (and flexible) approach to deleting records.

Tasks:
* [ ] Add "active" and "deleted" fields to metadata
* [ ] Update `rm` command to not delete the record, but rather update the metadata
* [ ] Add support for updating a record to "inactive" (`active=false`)
* [ ] Add config section `[rucksack.data_retention]`
  * [ ] add option `purge_on_quit` (default `false`)
  * [ ] add option `archive_deletes` (default `true`)
  * [ ] add option `delete_inactive` (default `false`)
* [ ] Add config section `[rucksack.display]`
  * [ ] add option `show_inactive`
  * [ ] add option `show_deleted`
* [ ] Update listing displays to optionally include status (active, inactive, deleted)
* [ ] Add flags for exporting data
  * [ ] `--include-inactive`
  * [ ] `--include-deleted`
* [ ] Add subcommands
  * [ ] `rm deleted`
  * [ ] `rm inactive`
* [ ] Add support for executing callbacks on quit/close
* [ ] Add logic for `purge_on_quit`
