### ISSUE TITLE
Enrich credentials, kinds, and definition of uniqueness

### ISSUE THREAD

**Issue by oubiwann** [oxur/rucksack#65]
Add:
* [x] Name (required for `Kind::Account`, `Kind::ServiceCredentials`, `Kind::Asymmetric`, and `Kind::Certificates`)
* [x] Account ID (only for `Kind::Account`)
* [x] Key (e.g, API Key; only for `Kind::ServiceCredentials`)
* [x] Secret (e.g., API Secret;  only for `Kind::ServiceCredentials`)
* [x] Public Key (only for `Kind::Asymmetric`)
* [x] Private Key (only for `Kind::Asymmetric`)
* [x] Public Cert (only for `Kind::Certificates`)
* [x] Private Cert (only for `Kind::Certificates`)
* [x] Root Cert (only for `Kind::Certificates`)

Also update `Kind` to include:
* [x] Certificates
* [x] Asymmetric (public/private keys)
* [x] Service Credentials

Distinguish between username/password and account/username/password:
* [x] Define `Password` for the former
* [x] Define `Account` for the latter (migrate old ones to `Password`)
* [x] Remove `Credentials` (migrate old ones to `Password`)

Add migrations for these:
* [x] `Certs`
* [x] `Kind`
* [x] All the bits that depend on those

Update ID to reflect these changes, allowing for similar secrets to exist (e.g., same user, same URL, but different company, etc.):
* [x] Add a default for `Metadata.category`
* [x] Migration for `category` will be the default value
* [x] Add migration for `name` to be the same as `username` from previous version of record
* [x] Update code for `Kind::Password` types' CRUD ops to copy `username` field to `name` field
* [x] Change ID to be a concatenation of `kind:category:name:url`

Flag updates for CRUD, listing, and export operations:
* [x] Add `--kind` flag (default being `password`)
* [x] Add `--category` flag (edits, listing, export/import)
* [ ] Change `--username` flag for edits to `--name`
* [ ] Add an alert when updating records with no URL (show existing data, ask to confirm overwrite)

Cleanup:
* [x] Rename various "account variables to "record" (unless they specifically refer to the `account` type)
* [x] Rename `Creds` to `Secrets`

**Comment by oubiwann** [comment]
Calling this done.
