### ISSUE TITLE
Split repo into app and library code bases

### ISSUE THREAD

**Issue by oubiwann** [oxur/rucksack#70]
https://users.rust-lang.org/t/what-is-the-idiomatic-way-to-manage-a-project-with-multiple-crates/6683

When this gets worked on, it should probably be in its own milestone, since this is a big (breaking) change.

Tasks
* [x] Move source code into new subdirs
* [x] Update source files for the new locations/library names
* [x] Ensure builds, tests, etc., continue to work
* [x] Get rucksack/README.md rendering

**Comment by oubiwann** [comment]
Related:
* #74 

(Some tasks that were originally part of ticket #70 have been moved there.)

**Comment by oubiwann** [comment]
So far so good. Any issue that crop up with this, I'll open as separate bug tickets.
