### ISSUE TITLE
Add support for 1password

### ISSUE THREAD

**Issue by oubiwann** [oxur/rucksack#77]
Features:
* [ ] Support reading the 1PUX file format
* [ ] Import exported 1pass CSV files
* [ ] Import exported 1pass 1PUX files
* [ ] Export data in the 1PUX file format

Resources:
* https://support.1password.com/1pux-format/
* https://support.1password.com/export/
* https://1password.com/downloads/command-line/
* https://developer.1password.com/docs/cli/
